package client

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

const (
	// DefaultSpecPath is the conventional OpenAPI document path.
	DefaultSpecPath = "openapi.json"
	// DefaultOutDir is the conventional generated-client directory (design §23.3).
	DefaultOutDir = "frontend/src/api/generated"

	openapiTypescriptPackage = "openapi-typescript@7.13.0"
	openapiFetchPackage      = "openapi-fetch@0.17.0"
	generatedBanner          = "Code generated by gombit client generate. DO NOT EDIT."
)

// Options configures TypeScript client generation.
type Options struct {
	WorkDir   string
	SpecPath  string
	OutDir    string
	DryRun    bool
	Force     bool
	NPXBinary string
	Stdout    io.Writer
	Stderr    io.Writer
}

// Generate writes schema.ts (via openapi-typescript) and the D10 client wrapper.
func Generate(ctx context.Context, opts Options) error {
	if ctx == nil {
		return errors.New("client: nil context")
	}
	if opts.WorkDir == "" {
		opts.WorkDir = "."
	}
	if opts.SpecPath == "" {
		opts.SpecPath = DefaultSpecPath
	}
	if opts.OutDir == "" {
		opts.OutDir = DefaultOutDir
	}
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}
	if opts.Stderr == nil {
		opts.Stderr = io.Discard
	}
	if opts.NPXBinary == "" {
		opts.NPXBinary = "npx"
	}

	specPath := opts.SpecPath
	if !filepath.IsAbs(specPath) {
		specPath = filepath.Join(opts.WorkDir, specPath)
	}
	// #nosec G304 -- spec path is a user-supplied generate input
	spec, err := os.ReadFile(specPath)
	if err != nil {
		return fmt.Errorf("client: read spec: %w", err)
	}
	if len(spec) == 0 {
		return errors.New("client: OpenAPI document is empty")
	}
	if err := validateSpecVersion(spec); err != nil {
		return err
	}
	// Normalize path keys to TypedAPIPrefix (/api/v1) for openapi-typescript.
	// Scaffolded pages call client.GET("/api/v1/..."); rewriteAPIRequest maps
	// those keys to the live prefix on the wire. The on-disk spec is unchanged
	// so examples/client contract-drift still compares live Huma paths.
	spec, err = rewriteSpecPathsForTypedClient(spec)
	if err != nil {
		return err
	}

	outDir := opts.OutDir
	if !filepath.IsAbs(outDir) {
		outDir = filepath.Join(opts.WorkDir, outDir)
	}

	files := []struct {
		name    string
		content []byte
		fromTS  bool
	}{
		{name: "schema.ts", fromTS: true},
		{name: "error.ts", content: []byte(errorTS)},
		{name: "client.ts", content: []byte(clientTS)},
	}

	for _, file := range files {
		path := filepath.Join(outDir, file.name)
		if err := checkOverwrite(path, opts.Force); err != nil {
			return err
		}
	}

	if opts.DryRun {
		for _, file := range files {
			path := filepath.Join(outDir, file.name)
			action := "create"
			if _, err := os.Stat(path); err == nil {
				action = "modify"
			}
			if _, err := fmt.Fprintf(opts.Stdout, "%s %s\n", action, displayPath(opts.WorkDir, path)); err != nil {
				return err
			}
		}
		return nil
	}

	if err := os.MkdirAll(outDir, 0o750); err != nil {
		return fmt.Errorf("client: create output directory: %w", err)
	}

	schema, err := runOpenAPITypescript(ctx, opts, spec, specPath, outDir)
	if err != nil {
		return err
	}
	files[0].content = schema

	for _, file := range files {
		path := filepath.Join(outDir, file.name)
		action := "created"
		if _, err := os.Stat(path); err == nil {
			action = "modified"
		}
		if err := os.WriteFile(path, file.content, 0o644); err != nil { //nolint:gosec // generated TS is a non-secret artifact
			return fmt.Errorf("client: write %s: %w", file.name, err)
		}
		if _, err := fmt.Fprintf(opts.Stdout, "%s %s\n", action, displayPath(opts.WorkDir, path)); err != nil {
			return err
		}
	}
	_, err = fmt.Fprintln(opts.Stdout, "add dependency: "+openapiFetchPackage)
	return err
}

func validateSpecVersion(spec []byte) error {
	var probe map[string]any
	if err := json.Unmarshal(spec, &probe); err != nil {
		return fmt.Errorf("client: parse spec: %w", err)
	}
	version, _ := probe["openapi"].(string)
	if strings.HasPrefix(version, "3.1.") || version == "3.1" {
		return nil
	}
	if version == "" {
		return errors.New("client: OpenAPI document is missing openapi 3.1 version")
	}
	return fmt.Errorf("client: openapi version %q is not 3.1", version)
}

func checkOverwrite(path string, force bool) error {
	// #nosec G304 -- path is the generator output file
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return fmt.Errorf("client: read %s: %w", path, err)
	}
	if force || bytes.Contains(data, []byte(generatedBanner)) {
		return nil
	}
	return fmt.Errorf("client: refuse to overwrite %s without --force (not generated by gombit)", path)
}

func runOpenAPITypescript(ctx context.Context, opts Options, spec []byte, specPath, outDir string) ([]byte, error) {
	// Sibling of the caller's document so relative $refs still resolve.
	// The original spec path is never overwritten.
	specFile, err := os.CreateTemp(filepath.Dir(specPath), "gombit-openapi-typed-*.json")
	if err != nil {
		return nil, fmt.Errorf("client: temp spec: %w", err)
	}
	specName := specFile.Name()
	if _, err := specFile.Write(spec); err != nil {
		_ = specFile.Close()
		_ = os.Remove(specName)
		return nil, fmt.Errorf("client: write temp spec: %w", err)
	}
	if err := specFile.Close(); err != nil {
		_ = os.Remove(specName)
		return nil, fmt.Errorf("client: close temp spec: %w", err)
	}
	defer func() { _ = os.Remove(specName) }()

	tmp, err := os.CreateTemp(outDir, "schema-*.ts")
	if err != nil {
		return nil, fmt.Errorf("client: temp schema: %w", err)
	}
	tmpName := tmp.Name()
	_ = tmp.Close()
	defer func() { _ = os.Remove(tmpName) }()

	cmd := exec.CommandContext(ctx, opts.NPXBinary, "--yes", openapiTypescriptPackage, specName, "-o", tmpName) //nolint:gosec // pinned package and generator temp paths
	cmd.Dir = opts.WorkDir
	cmd.Stderr = opts.Stderr
	cmd.Stdout = opts.Stderr
	if err := cmd.Run(); err != nil {
		return nil, fmt.Errorf("client: %s %s: %w", opts.NPXBinary, openapiTypescriptPackage, err)
	}
	// #nosec G304 -- tmpName is created in this function
	generated, err := os.ReadFile(tmpName)
	if err != nil {
		return nil, fmt.Errorf("client: read generated schema: %w", err)
	}
	var b strings.Builder
	b.WriteString("/**\n * ")
	b.WriteString(generatedBanner)
	b.WriteString("\n */\n")
	b.Write(generated)
	return []byte(b.String()), nil
}

func displayPath(workDir, path string) string {
	rel, err := filepath.Rel(workDir, path)
	if err != nil {
		return path
	}
	return filepath.ToSlash(rel)
}
