package client

const errorTS = `/**
 * Code generated by gombit client generate. DO NOT EDIT.
 */

/** D10 error envelope: {"error":{code,message,fields?,request_id}}. */
export type D10ErrorBody = {
  error: {
    code: string;
    message: string;
    fields?: { [key: string]: string[] };
    request_id?: string;
  };
};

export function isD10ErrorBody(value: unknown): value is D10ErrorBody {
  if (value === null || typeof value !== "object") {
    return false;
  }
  const error = (value as { error?: unknown }).error;
  if (error === null || typeof error !== "object") {
    return false;
  }
  const body = error as { code?: unknown; message?: unknown };
  return typeof body.code === "string" && typeof body.message === "string";
}

export function parseD10Error(value: unknown): D10ErrorBody | undefined {
  if (isD10ErrorBody(value)) {
    return value;
  }
  return undefined;
}

/** Typed application error mapped from the D10 envelope. */
export class ContractError extends Error {
  readonly code: string;
  readonly status: number;
  readonly fields?: { [key: string]: string[] };
  readonly requestId?: string;

  constructor(
    code: string,
    message: string,
    status: number,
    fields?: { [key: string]: string[] },
    requestId?: string,
  ) {
    super(message);
    this.name = "ContractError";
    this.code = code;
    this.status = status;
    this.fields = fields;
    this.requestId = requestId;
  }

  static fromResponse(response: Response, body: unknown): ContractError {
    const parsed = parseD10Error(body);
    if (parsed) {
      return new ContractError(
        parsed.error.code,
        parsed.error.message,
        response.status,
        parsed.error.fields,
        parsed.error.request_id,
      );
    }
    const fallback = response.statusText.trim() || "request failed";
    return new ContractError("error", fallback, response.status);
  }
}
`

const clientTS = `/**
 * Code generated by gombit client generate. DO NOT EDIT.
 */

import createClient from "openapi-fetch";
import type { paths } from "./schema";
import { ContractError, isD10ErrorBody, parseD10Error } from "./error";

export type { paths };
export { ContractError, isD10ErrorBody, parseD10Error };
export type { D10ErrorBody } from "./error";

export type GombitClientOptions = {
  baseUrl: string;
  /**
   * Returns the in-memory access token for this request.
   * Supply the in-memory access token only. Never persist it in web storage.
   */
  getAccessToken?: () => string | undefined;
};

export function createGombitClient(options: GombitClientOptions) {
  const client = createClient<paths>({ baseUrl: options.baseUrl });
  client.use({
    onRequest({ request }) {
      const token = options.getAccessToken?.();
      if (token) {
        request.headers.set("Authorization", ` + "`Bearer ${token}`" + `);
      }
      return request;
    },
  });
  return client;
}

export async function unwrap<T>(result: {
  data?: T;
  error?: unknown;
  response: Response;
}): Promise<T> {
  if (result.error !== undefined || !result.response.ok) {
    throw ContractError.fromResponse(result.response, result.error);
  }
  if (result.data === undefined) {
    throw new ContractError("empty_response", "Empty response", result.response.status);
  }
  return result.data;
}
`
