// Code generated by gombit make command. DO NOT EDIT.
package commands

import (
	"fmt"

	"github.com/gombit-dev/gombit/cli"
)

// NewGreetCommand returns the greet management command.
// Attach it with cli.AddCommand from RegisterCommands (D13 / ADR-014).
func NewGreetCommand() *cli.Command {
	return &cli.Command{
		Use:   "greet",
		Short: "Run the greet management command",
		RunE: func(cmd *cli.Command, args []string) error {
			_, err := fmt.Fprintln(cmd.OutOrStdout(), "greet: ok")
			return err
		},
	}
}
