/**
 * Code generated by gombit make resource. DO NOT EDIT.
 *
 * Registry of resources created by `gombit make resource`. Re-run that
 * command to refresh this file. Vanilla list/table + create form pages
 * import types from ./api/generated — run `gombit client generate` or
 * `gombit dev` after the API is up. Full React Router + RHF is M5-1.
 */

export function mountIfResource(_root: HTMLElement): boolean {
  return false;
}
