package commandgen

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// Generate writes a management command into an existing Gombit app.
func Generate(ctx context.Context, opts Options) error {
	if ctx == nil {
		return errors.New("commandgen: nil context")
	}
	if err := ctx.Err(); err != nil {
		return err
	}
	if err := opts.normalize(); err != nil {
		return err
	}
	if err := opts.validateAppLayout(); err != nil {
		return err
	}

	name, err := parseCommandName(opts.Name, opts.Package)
	if err != nil {
		return err
	}
	module, err := readModulePath(opts.WorkDir)
	if err != nil {
		return err
	}

	commandRel := opts.commandRel(name.Package, name.FileBase)
	commandsRel := opts.commandsRel(name.Package)
	importPath := module + "/internal/" + name.Package

	commandSrc, err := renderCommandFile(name)
	if err != nil {
		return err
	}

	commandsPath := filepath.Join(opts.WorkDir, filepath.FromSlash(commandsRel))
	commandsSrc, err := os.ReadFile(commandsPath) // #nosec G304 -- application file under the user work dir
	if err != nil {
		if !errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("commandgen: read %s: %w", commandsRel, err)
		}
		commandsSrc, err = renderCommandsFile(name.Package)
		if err != nil {
			return err
		}
	}
	newCommands, err := AddCommandCall(commandsSrc, name.Constructor)
	if err != nil {
		return err
	}

	mainPath := filepath.Join(opts.WorkDir, filepath.FromSlash(gombitMainRel))
	mainSrc, err := os.ReadFile(mainPath) // #nosec G304 -- application file under the user work dir
	if err != nil {
		return fmt.Errorf("commandgen: read %s: %w", gombitMainRel, err)
	}
	newMain, err := AddImportAndRegister(mainSrc, importPath, name.Package)
	if err != nil {
		return err
	}

	files := []fileSpec{
		{relPath: commandRel, content: commandSrc},
		{relPath: commandsRel, content: newCommands, owned: true},
		{relPath: gombitMainRel, content: newMain, owned: true},
	}
	sort.Slice(files, func(i, j int) bool {
		return files[i].relPath < files[j].relPath
	})

	planned, err := planWrites(opts, files)
	if err != nil {
		return err
	}
	for _, item := range planned {
		if _, err := fmt.Fprintf(opts.Stdout, "%s %s\n", item.action, item.display); err != nil {
			return err
		}
		if opts.DryRun || !item.write {
			continue
		}
		full := filepath.Join(opts.WorkDir, filepath.FromSlash(item.relPath))
		if err := os.MkdirAll(filepath.Dir(full), 0o750); err != nil {
			return fmt.Errorf("commandgen: mkdir %s: %w", filepath.Dir(full), err)
		}
		if err := os.WriteFile(full, item.content, 0o644); err != nil { //nolint:gosec // generated source is a non-secret artifact
			return fmt.Errorf("commandgen: write %s: %w", item.display, err)
		}
	}
	return nil
}

type plannedFile struct {
	relPath string
	display string
	content []byte
	action  string
	write   bool
}

func planWrites(opts Options, files []fileSpec) ([]plannedFile, error) {
	var planned []plannedFile
	for _, file := range files {
		full := filepath.Join(opts.WorkDir, filepath.FromSlash(file.relPath))
		display, err := displayPath(opts.WorkDir, full)
		if err != nil {
			return nil, err
		}
		existing, err := os.ReadFile(full) // #nosec G304 -- generator output path
		if err != nil && !errors.Is(err, os.ErrNotExist) {
			return nil, fmt.Errorf("commandgen: read %s: %w", display, err)
		}
		exists := err == nil
		if exists && bytes.Equal(existing, file.content) {
			continue
		}
		if exists {
			if err := checkOverwrite(display, existing, file, opts.Force); err != nil {
				return nil, err
			}
		}
		action := "create"
		if exists {
			action = "modify"
		}
		planned = append(planned, plannedFile{
			relPath: file.relPath,
			display: display,
			content: file.content,
			action:  action,
			write:   true,
		})
	}
	return planned, nil
}

func checkOverwrite(display string, existing []byte, file fileSpec, force bool) error {
	if force {
		return nil
	}
	if file.owned {
		return nil
	}
	if bytes.Contains(existing, []byte(GeneratedBanner)) {
		return fmt.Errorf("commandgen: refuse to overwrite %s without --force (generated file differs from this run)", display)
	}
	return fmt.Errorf("commandgen: refuse to overwrite %s without --force (not generated by gombit)", display)
}

func readModulePath(workDir string) (string, error) {
	path := filepath.Join(workDir, "go.mod")
	data, err := os.ReadFile(path) // #nosec G304 -- go.mod inside the application work dir
	if err != nil {
		return "", fmt.Errorf("commandgen: read go.mod: %w", err)
	}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if strings.HasPrefix(line, "module ") {
			module := strings.TrimSpace(strings.TrimPrefix(line, "module "))
			if module == "" {
				break
			}
			return module, nil
		}
	}
	return "", errors.New("commandgen: go.mod is missing a module path")
}

func displayPath(workDir, full string) (string, error) {
	rel, err := filepath.Rel(workDir, full)
	if err != nil {
		return "", fmt.Errorf("commandgen: relative path: %w", err)
	}
	return filepath.ToSlash(rel), nil
}
