package commandgen

import (
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
)

const (
	// GeneratedBanner marks command files written by this generator. User-owned
	// files without the banner are refused unless --force is set.
	GeneratedBanner = "Code generated by gombit make command. DO NOT EDIT."

	defaultPackage   = "commands"
	gombitMainRel    = "cmd/gombit/main.go"
	serverMainRel    = "cmd/server/main.go"
	gombitYAMLRel    = "gombit.yaml"
	commandsFileName = "commands.go"
)

// Options configures management-command generation inside an existing app.
type Options struct {
	WorkDir string
	Name    string
	Package string
	DryRun  bool
	Force   bool
	Stdout  io.Writer
	Stderr  io.Writer
}

func (opts *Options) normalize() error {
	if opts.Stdout == nil {
		opts.Stdout = io.Discard
	}
	if opts.Stderr == nil {
		opts.Stderr = io.Discard
	}
	if opts.WorkDir == "" {
		opts.WorkDir = "."
	}
	workDir, err := filepath.Abs(opts.WorkDir)
	if err != nil {
		return fmt.Errorf("commandgen: resolve work dir: %w", err)
	}
	opts.WorkDir = workDir
	if opts.Package == "" {
		opts.Package = defaultPackage
	}
	return nil
}

func (opts Options) validateAppLayout() error {
	for _, rel := range []string{"go.mod", gombitMainRel} {
		if err := opts.requireFile(rel); err != nil {
			return err
		}
	}
	return opts.requireGeneratedApp()
}

func (opts Options) requireFile(rel string) error {
	path := filepath.Join(opts.WorkDir, filepath.FromSlash(rel))
	if _, err := os.Stat(path); err != nil {
		if errors.Is(err, os.ErrNotExist) {
			return fmt.Errorf("commandgen: %s not found; run this command from a gombit new application directory", rel)
		}
		return fmt.Errorf("commandgen: stat %s: %w", rel, err)
	}
	return nil
}

func (opts Options) requireGeneratedApp() error {
	serverPath := filepath.Join(opts.WorkDir, filepath.FromSlash(serverMainRel))
	yamlPath := filepath.Join(opts.WorkDir, filepath.FromSlash(gombitYAMLRel))
	_, serverErr := os.Stat(serverPath)
	_, yamlErr := os.Stat(yamlPath)
	serverMissing := errors.Is(serverErr, os.ErrNotExist)
	yamlMissing := errors.Is(yamlErr, os.ErrNotExist)
	if serverErr != nil && !serverMissing {
		return fmt.Errorf("commandgen: stat %s: %w", serverMainRel, serverErr)
	}
	if yamlErr != nil && !yamlMissing {
		return fmt.Errorf("commandgen: stat %s: %w", gombitYAMLRel, yamlErr)
	}
	if serverMissing && yamlMissing {
		return fmt.Errorf("commandgen: not a gombit application directory (missing %s and %s); run this command from a gombit new application directory", serverMainRel, gombitYAMLRel)
	}
	return nil
}

func (opts Options) commandsRel(pkg string) string {
	return filepath.ToSlash(filepath.Join("internal", pkg, commandsFileName))
}

func (opts Options) commandRel(pkg, fileBase string) string {
	return filepath.ToSlash(filepath.Join("internal", pkg, fileBase+".go"))
}
