package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"

	"github.com/LAA-Software-Engineering/gombit/client"
)

func runClient(ctx context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	if len(args) == 0 {
		clientUsage(stderr)
		return errors.New("gombit client: subcommand is required")
	}
	if args[0] != "generate" {
		clientUsage(stderr)
		return fmt.Errorf("gombit client: unknown subcommand %q", args[0])
	}
	return runClientGenerate(ctx, args[1:], stdout, stderr)
}

func runClientGenerate(ctx context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	flags := flag.NewFlagSet("gombit client generate", flag.ContinueOnError)
	flags.SetOutput(stderr)
	spec := flags.String("spec", client.DefaultSpecPath, "OpenAPI 3.1 document path")
	out := flags.String("out", client.DefaultOutDir, "output directory for generated TypeScript")
	dryRun := flags.Bool("dry-run", false, "print files that would be written without writing")
	force := flags.Bool("force", false, "overwrite files that were not generated by gombit")
	npx := flags.String("npx", "npx", "npx binary used to run openapi-typescript")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		flags.Usage()
		return fmt.Errorf("gombit client generate: unexpected argument %q", flags.Arg(0))
	}

	return client.Generate(ctx, client.Options{
		WorkDir:   ".",
		SpecPath:  *spec,
		OutDir:    *out,
		DryRun:    *dryRun,
		Force:     *force,
		NPXBinary: *npx,
		Stdout:    stdout,
		Stderr:    stderr,
	})
}

func clientUsage(w io.Writer) {
	_, _ = fmt.Fprintln(w, "available client subcommands:")
	_, _ = fmt.Fprintln(w, "  generate [--spec openapi.json] [--out frontend/src/api/generated] [--dry-run] [--force]")
}
