package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"

	"github.com/LAA-Software-Engineering/gombit/client"
)

func runClient(ctx context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	if len(args) == 0 {
		clientUsage(stderr)
		return errors.New("gombit client: subcommand is required")
	}
	switch args[0] {
	case "generate":
		return runClientGenerate(ctx, args[1:], stdout, stderr)
	case "check":
		return runClientCheck(ctx, args[1:], stdout, stderr)
	default:
		clientUsage(stderr)
		return fmt.Errorf("gombit client: unknown subcommand %q", args[0])
	}
}

func runClientGenerate(ctx context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	flags := flag.NewFlagSet("gombit client generate", flag.ContinueOnError)
	flags.SetOutput(stderr)
	spec := flags.String("spec", client.DefaultSpecPath, "OpenAPI 3.1 document path")
	out := flags.String("out", client.DefaultOutDir, "output directory for generated TypeScript")
	dryRun := flags.Bool("dry-run", false, "print files that would be written without writing")
	force := flags.Bool("force", false, "overwrite files that were not generated by gombit")
	npx := flags.String("npx", "npx", "npx binary used to run openapi-typescript")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		flags.Usage()
		return fmt.Errorf("gombit client generate: unexpected argument %q", flags.Arg(0))
	}

	return client.Generate(ctx, client.Options{
		WorkDir:   ".",
		SpecPath:  *spec,
		OutDir:    *out,
		DryRun:    *dryRun,
		Force:     *force,
		NPXBinary: *npx,
		Stdout:    stdout,
		Stderr:    stderr,
	})
}

func runClientCheck(ctx context.Context, args []string, stdout io.Writer, stderr io.Writer) error {
	flags := flag.NewFlagSet("gombit client check", flag.ContinueOnError)
	flags.SetOutput(stderr)
	spec := flags.String("spec", client.SampleSpecPath, "committed OpenAPI 3.1 document path")
	out := flags.String("out", client.SampleOutDir, "committed generated TypeScript directory")
	write := flags.Bool("write", false, "rewrite committed fixtures instead of reporting drift")
	npx := flags.String("npx", "npx", "npx binary used to run openapi-typescript")
	if err := flags.Parse(args); err != nil {
		return err
	}
	if flags.NArg() != 0 {
		flags.Usage()
		return fmt.Errorf("gombit client check: unexpected argument %q", flags.Arg(0))
	}

	return client.CheckDrift(ctx, client.DriftOptions{
		WorkDir:   ".",
		SpecPath:  *spec,
		OutDir:    *out,
		Write:     *write,
		NPXBinary: *npx,
		Stdout:    stdout,
		Stderr:    stderr,
	})
}

func clientUsage(w io.Writer) {
	_, _ = fmt.Fprintln(w, "available client subcommands:")
	_, _ = fmt.Fprintln(w, "  generate [--spec openapi.json] [--out frontend/src/api/generated] [--dry-run] [--force] [--npx npx]")
	_, _ = fmt.Fprintln(w, "  check [--write] [--spec examples/client/openapi.json] [--out examples/client/frontend/src/api/generated] [--npx npx]")
}
