package cli

import (
	"errors"
	"fmt"
	"io"

	"github.com/gombit-dev/gombit/client"
	"github.com/spf13/cobra"
)

func newClientCommand(stdout io.Writer, stderr io.Writer) *cobra.Command {
	cmd := silence(&cobra.Command{
		Use:   "client",
		Short: "TypeScript client commands",
		Args:  cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			clientUsage(stderr)
			if len(args) == 0 {
				return errors.New("gombit client: subcommand is required")
			}
			return fmt.Errorf("gombit client: unknown subcommand %q", args[0])
		},
	})
	cmd.AddCommand(newClientGenerateCommand(stdout, stderr))
	cmd.AddCommand(newClientCheckCommand(stdout, stderr))
	return cmd
}

func newClientGenerateCommand(stdout io.Writer, stderr io.Writer) *cobra.Command {
	cmd := silence(&cobra.Command{
		Use:   "generate",
		Short: "Generate a TypeScript client from an OpenAPI 3.1 document",
		Args:  cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) != 0 {
				return fmt.Errorf("gombit client generate: unexpected argument %q", args[0])
			}
			spec, err := cmd.Flags().GetString("spec")
			if err != nil {
				return err
			}
			out, err := cmd.Flags().GetString("out")
			if err != nil {
				return err
			}
			dryRun, err := cmd.Flags().GetBool("dry-run")
			if err != nil {
				return err
			}
			force, err := cmd.Flags().GetBool("force")
			if err != nil {
				return err
			}
			npx, err := cmd.Flags().GetString("npx")
			if err != nil {
				return err
			}
			return client.Generate(cmd.Context(), client.Options{
				WorkDir:   ".",
				SpecPath:  spec,
				OutDir:    out,
				DryRun:    dryRun,
				Force:     force,
				NPXBinary: npx,
				Stdout:    stdout,
				Stderr:    stderr,
			})
		},
	})
	cmd.Flags().String("spec", client.DefaultSpecPath, "OpenAPI 3.1 document path")
	cmd.Flags().String("out", client.DefaultOutDir, "output directory for generated TypeScript")
	cmd.Flags().Bool("dry-run", false, "print files that would be written without writing")
	cmd.Flags().Bool("force", false, "overwrite files that were not generated by gombit")
	cmd.Flags().String("npx", "npx", "npx binary used to run openapi-typescript")
	return cmd
}

func newClientCheckCommand(stdout io.Writer, stderr io.Writer) *cobra.Command {
	cmd := silence(&cobra.Command{
		Use:   "check",
		Short: "Fail when the committed TypeScript client drifts from the contract",
		Long: `Fail when the committed TypeScript client drifts from the contract.

Without --url, the comparison source is an in-process huma.API (the
framework's own SampleApp by default), which only exists inside this
repository — that mode backs the framework's own CI check against
examples/client/. Generated apps have no Go-level access to their API from
a separately compiled gombit binary, so pass --url to fetch the live
/openapi.json from a running app instead:

  gombit client check --url http://127.0.0.1:8080/openapi.json`,
		Args: cobra.ArbitraryArgs,
		RunE: func(cmd *cobra.Command, args []string) error {
			if len(args) != 0 {
				return fmt.Errorf("gombit client check: unexpected argument %q", args[0])
			}
			spec, err := cmd.Flags().GetString("spec")
			if err != nil {
				return err
			}
			out, err := cmd.Flags().GetString("out")
			if err != nil {
				return err
			}
			write, err := cmd.Flags().GetBool("write")
			if err != nil {
				return err
			}
			npx, err := cmd.Flags().GetString("npx")
			if err != nil {
				return err
			}
			rawURL, err := cmd.Flags().GetString("url")
			if err != nil {
				return err
			}
			opts := client.DriftOptions{
				WorkDir:   ".",
				SpecPath:  spec,
				OutDir:    out,
				Write:     write,
				NPXBinary: npx,
				Stdout:    stdout,
				Stderr:    stderr,
			}
			if rawURL != "" {
				specBytes, err := fetchOpenAPI(cmd.Context(), rawURL)
				if err != nil {
					return err
				}
				opts.SpecBytes = specBytes
			}
			return client.CheckDrift(cmd.Context(), opts)
		},
	})
	cmd.Flags().String("spec", client.DefaultSpecPath, "committed OpenAPI 3.1 document path")
	cmd.Flags().String("out", client.DefaultOutDir, "committed generated TypeScript directory")
	cmd.Flags().Bool("write", false, "rewrite committed fixtures instead of reporting drift")
	cmd.Flags().String("npx", "npx", "npx binary used to run openapi-typescript")
	cmd.Flags().String("url", "", "URL of a live /openapi.json to compare against instead of an in-process API (required outside this repository)")
	return cmd
}
