/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

// Vanilla list/table + create form pages. Types are imported from
// ./api/generated (gombit client generate / gombit dev). Full React
// Router + React Hook Form is M5-1. API prefix: /api/v1
// Access tokens stay in memory; this file does not use localStorage.

import { renderBookList } from "./book/list";
import { renderBookForm } from "./book/form";

export type GeneratedResource = {
  slug: string;
  title: string;
  mountList: (root: HTMLElement) => Promise<void> | void;
  mountForm: (root: HTMLElement) => Promise<void> | void;
};

export const generatedResources: GeneratedResource[] = [
  {
    slug: "book",
    title: "Book",
    mountList: renderBookList,
    mountForm: renderBookForm,
  },
];

export function mountIfResource(root: HTMLElement): boolean {
  const params = new URLSearchParams(window.location.search);
  const slug = params.get("resource");
  if (!slug) {
    if (generatedResources.length === 0) {
      return false;
    }
    renderResourceIndex(root);
    return true;
  }
  const resource = generatedResources.find((item) => item.slug === slug);
  if (!resource) {
    return false;
  }
  if (params.get("view") === "new") {
    void resource.mountForm(root);
  } else {
    void resource.mountList(root);
  }
  return true;
}

function renderResourceIndex(root: HTMLElement): void {
  root.replaceChildren();
  const heading = document.createElement("h1");
  heading.textContent = "Resources";
  root.append(heading);
  const list = document.createElement("ul");
  for (const resource of generatedResources) {
    const item = document.createElement("li");
    const link = document.createElement("a");
    link.href = `?resource=${resource.slug}`;
    link.textContent = resource.title;
    item.append(link);
    list.append(item);
  }
  root.append(list);
}
