/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

// React list + create-form pages. Types come from ./api/generated
// (gombit client generate / gombit dev). OpenAPI path keys use /api/v1;
// createAppClient rewrites them to the live GOMBIT_API_PREFIX.
// Access tokens stay in memory; this file does not use web storage.

import type { RouteObject } from "react-router";

import { BookListPage } from "./book/list";
import { BookFormPage } from "./book/form";

export type GeneratedResource = {
  slug: string;
  title: string;
  listPath: string;
  createPath: string;
};

export const generatedResources: GeneratedResource[] = [
  {
    slug: "book",
    title: "Book",
    listPath: "/books",
    createPath: "/books/new",
  },
];

export const generatedResourceRoutes: RouteObject[] = [
  { path: "books", element: <BookListPage /> },
  { path: "books/new", element: <BookFormPage /> },
];
