/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

import type { paths } from "../api/generated/schema";

const apiBase = import.meta.env.VITE_API_URL || "/api/v1";

type CreateBody =
  paths["/api/v1/books"]["post"]["requestBody"]["content"]["application/json"];

/**
 * Vanilla create form. Request/response types come from the generated
 * OpenAPI client. Run gombit client generate or gombit dev after adding
 * routes so frontend/src/api/generated exists.
 */
export function renderBookForm(root: HTMLElement): void {
  root.replaceChildren();
  const heading = document.createElement("h1");
  heading.textContent = "New Book";
  root.append(heading);

  const back = document.createElement("p");
  const link = document.createElement("a");
  link.href = "?resource=book";
  link.textContent = "Back to list";
  back.append(link);
  root.append(back);

  const form = document.createElement("form");
  const titleLabel = document.createElement("label");
  titleLabel.textContent = "Title";
  const titleInput = document.createElement("input");
  titleInput.setAttribute("type", "text");
  titleInput.setAttribute("name", "title");
  titleInput.setAttribute("required", "true");
  titleLabel.append(titleInput);
  form.append(titleLabel);
  const submit = document.createElement("button");
  submit.type = "submit";
  submit.textContent = "Create";
  form.append(submit);
  const status = document.createElement("p");
  root.append(form, status);

  form.addEventListener("submit", (event) => {
    event.preventDefault();
    const payload = { title: readTitle() } as CreateBody;
    void fetch(`${apiBase}/books`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify(payload),
    })
      .then(async (response) => {
        if (!response.ok) {
          status.textContent = `create failed (${response.status})`;
          return;
        }
        window.location.search = "?resource=book";
      })
      .catch((err: unknown) => {
        status.textContent = err instanceof Error ? err.message : "request failed";
      });
  });
  function readTitle(): string {
    return (titleInput as HTMLInputElement).value;
  }
}
