/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

import { useState } from "react";
import { useForm } from "react-hook-form";
import { Link, useNavigate } from "react-router";

import { useApiClient } from "../api/client";
import { applyContractErrors } from "../api/formErrors";
import { unwrap } from "../api/generated/client";
import type { paths } from "../api/generated/schema";

const createPath = "/api/v1/books" as const;

type CreateBody =
  paths[typeof createPath]["post"]["requestBody"]["content"]["application/json"];

type FormValues = {
  title: string;
};

/**
 * React Hook Form create page. Request/response types come from the
 * generated OpenAPI client. D10 error.fields map through applyContractErrors.
 * Run gombit client generate or gombit dev after adding routes.
 */
export function BookFormPage() {
  const client = useApiClient();
  const navigate = useNavigate();
  const [status, setStatus] = useState("");
  const {
    register,
    handleSubmit,
    setError,
    formState: { errors, isSubmitting },
  } = useForm<FormValues>({
    defaultValues: { title: "" },
  });

  async function onSubmit(values: FormValues) {
    setStatus("");
    try {
      await unwrap(await client.POST(createPath, { body: values as CreateBody }));
      navigate("/books");
    } catch (err: unknown) {
      if (!applyContractErrors(setError, err)) {
        setStatus(err instanceof Error ? err.message : "request failed");
      }
    }
  }

  return (
    <section>
      <h1>New Book</h1>
      <p>
        <Link to="/books">Back to list</Link>
      </p>
      <form onSubmit={handleSubmit(onSubmit)}>
        <label>
          Title
          <input type="text" {...register("title", { required: true })} />
        </label>
        {errors.title?.message ? <p>{errors.title.message}</p> : null}
        <button type="submit" disabled={isSubmitting}>
          Create
        </button>
      </form>
      {status ? <p>{status}</p> : null}
    </section>
  );
}
