/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

import type { paths } from "../api/generated/schema";

const apiBase = import.meta.env.VITE_API_URL || "/api/v1";

type ListResponse =
  paths["/api/v1/books"]["get"]["responses"][200]["content"]["application/json"];

/**
 * Vanilla list/table page. Types come from the generated OpenAPI client
 * (gombit client generate / gombit dev). Do not duplicate API DTOs here.
 */
export async function renderBookList(root: HTMLElement): Promise<void> {
  root.replaceChildren();
  const heading = document.createElement("h1");
  heading.textContent = "Books";
  root.append(heading);

  const nav = document.createElement("p");
  const home = document.createElement("a");
  home.href = "?";
  home.textContent = "All resources";
  const create = document.createElement("a");
  create.href = "?resource=book&view=new";
  create.textContent = "New Book";
  nav.append(home, document.createTextNode(" · "), create);
  root.append(nav);

  const table = document.createElement("table");
  const thead = document.createElement("thead");
  const headerRow = document.createElement("tr");
  for (const label of ["id", "title"]) {
    const th = document.createElement("th");
    th.textContent = label;
    headerRow.append(th);
  }
  thead.append(headerRow);
  table.append(thead);
  const tbody = document.createElement("tbody");
  table.append(tbody);
  root.append(table);

  const status = document.createElement("p");
  root.append(status);

  try {
    const response = await fetch(`${apiBase}/books`);
    const body = (await response.json()) as ListResponse;
    const rows = Array.isArray(body.data) ? body.data : [];
    if (rows.length === 0) {
      status.textContent = "No books yet.";
      return;
    }
    for (const row of rows) {
      const tr = document.createElement("tr");
      const values: unknown[] = [(row as { id?: unknown }).id, (row as { title?: unknown }).title];
      for (const value of values) {
        const td = document.createElement("td");
        td.textContent = value == null ? "" : String(value);
        tr.append(td);
      }
      tbody.append(tr);
    }
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : "request failed";
    status.textContent = message;
  }
}
