/**
 * Code generated by gombit make resource. DO NOT EDIT.
 */

import { useEffect, useState } from "react";
import { Link } from "react-router";

import { useApiClient } from "../api/client";
import { unwrap } from "../api/generated/client";
import type { paths } from "../api/generated/schema";

const listPath = "/api/v1/books" as const;

type ListResponse =
  paths[typeof listPath]["get"]["responses"][200]["content"]["application/json"];
type ListRow = NonNullable<ListResponse["data"]>[number];

/**
 * React list/table page. Types come from the generated OpenAPI client
 * (gombit client generate / gombit dev). Do not duplicate API DTOs here.
 */
export function BookListPage() {
  const client = useApiClient();
  const [rows, setRows] = useState<ListRow[]>([]);
  const [status, setStatus] = useState("Loading…");

  useEffect(() => {
    let cancelled = false;
    void (async () => {
      try {
        const listed = await unwrap(await client.GET(listPath));
        if (cancelled) {
          return;
        }
        const data = Array.isArray(listed.data) ? listed.data : [];
        setRows(data);
        setStatus(data.length === 0 ? "No books yet." : "");
      } catch (err: unknown) {
        if (cancelled) {
          return;
        }
        setStatus(err instanceof Error ? err.message : "request failed");
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [client]);

  return (
    <section>
      <h1>Books</h1>
      <p>
        <Link to="/books/new">New Book</Link>
      </p>
      <table>
        <thead>
          <tr>
            {["id", "title"].map((label) => (
              <th key={label}>{label}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((row, index) => {
            const record = row as { id?: unknown; title?: unknown };
            const values: unknown[] = [record.id, record.title];
            const key = record.id == null ? String(index) : String(record.id);
            return (
              <tr key={key}>
                {values.map((value, cell) => (
                  <td key={cell}>{value == null ? "" : String(value)}</td>
                ))}
              </tr>
            );
          })}
        </tbody>
      </table>
      {status ? <p>{status}</p> : null}
    </section>
  );
}
